export interface Job {
  id: string;
  title: string;
  titleHindi: string;
  department: string;
  departmentHindi: string;
  category: string;
  vacancies: number;
  qualification: string;
  qualificationHindi: string;
  ageLimit: string;
  ageLimitHindi: string;
  lastDate: string;
  salary: string;
  salaryHindi: string;
  website: string;
  status: "Active" | "Closed" | "Upcoming";
  icon: string;
}

export const jobs: Job[] = [
  {
    id: "ssc-cgl-2025",
    title: "SSC CGL Recruitment",
    titleHindi: "एसएससी सीजीएल भर्ती",
    department: "Staff Selection Commission",
    departmentHindi: "कर्मचारी चयन आयोग",
    category: "Central Govt",
    vacancies: 14582,
    qualification: "Bachelor's Degree",
    qualificationHindi: "स्नातक डिग्री",
    ageLimit: "18-32 years",
    ageLimitHindi: "18-32 वर्ष",
    lastDate: "2025-07-04",
    salary: "₹25,500 - ₹81,100",
    salaryHindi: "₹25,500 - ₹81,100",
    website: "https://ssc.gov.in",
    status: "Active",
    icon: "Building2"
  },
  {
    id: "ssc-chsl-2025",
    title: "SSC CHSL Recruitment",
    titleHindi: "एसएससी सीएचएसएल भर्ती",
    department: "Staff Selection Commission",
    departmentHindi: "कर्मचारी चयन आयोग",
    category: "Central Govt",
    vacancies: 3131,
    qualification: "12th Pass",
    qualificationHindi: "12वीं पास",
    ageLimit: "18-27 years",
    ageLimitHindi: "18-27 वर्ष",
    lastDate: "2025-07-18",
    salary: "₹19,900 - ₹63,200",
    salaryHindi: "₹19,900 - ₹63,200",
    website: "https://ssc.gov.in",
    status: "Active",
    icon: "Building2"
  },
  {
    id: "ssc-gd-2026",
    title: "SSC GD Constable",
    titleHindi: "एसएससी जीडी कांस्टेबल",
    department: "Central Armed Police Forces",
    departmentHindi: "केंद्रीय सशस्त्र पुलिस बल",
    category: "Defense",
    vacancies: 25847,
    qualification: "10th Pass",
    qualificationHindi: "10वीं पास",
    ageLimit: "18-23 years",
    ageLimitHindi: "18-23 वर्ष",
    lastDate: "2025-12-31",
    salary: "₹21,700 - ₹69,100",
    salaryHindi: "₹21,700 - ₹69,100",
    website: "https://ssc.gov.in",
    status: "Active",
    icon: "Shield"
  },
  {
    id: "rrb-group-d-2025",
    title: "RRB Group D",
    titleHindi: "आरआरबी ग्रुप डी",
    department: "Indian Railways",
    departmentHindi: "भारतीय रेलवे",
    category: "Railway",
    vacancies: 32438,
    qualification: "10th Pass",
    qualificationHindi: "10वीं पास",
    ageLimit: "18-33 years",
    ageLimitHindi: "18-33 वर्ष",
    lastDate: "2025-02-22",
    salary: "₹18,000 - ₹56,900",
    salaryHindi: "₹18,000 - ₹56,900",
    website: "https://rrbcdg.gov.in",
    status: "Active",
    icon: "Train"
  },
  {
    id: "rrb-alp-2025",
    title: "RRB ALP Recruitment",
    titleHindi: "आरआरबी एएलपी भर्ती",
    department: "Indian Railways",
    departmentHindi: "भारतीय रेलवे",
    category: "Railway",
    vacancies: 9970,
    qualification: "ITI/Diploma",
    qualificationHindi: "आईटीआई/डिप्लोमा",
    ageLimit: "18-30 years",
    ageLimitHindi: "18-30 वर्ष",
    lastDate: "2025-05-11",
    salary: "₹19,900 - ₹63,200",
    salaryHindi: "₹19,900 - ₹63,200",
    website: "https://rrbcdg.gov.in",
    status: "Active",
    icon: "Train"
  },
  {
    id: "sbi-po-2025",
    title: "SBI Probationary Officer",
    titleHindi: "एसबीआई प्रोबेशनरी ऑफिसर",
    department: "State Bank of India",
    departmentHindi: "स्टेट बैंक ऑफ इंडिया",
    category: "Banking",
    vacancies: 541,
    qualification: "Bachelor's Degree",
    qualificationHindi: "स्नातक डिग्री",
    ageLimit: "21-30 years",
    ageLimitHindi: "21-30 वर्ष",
    lastDate: "2025-07-14",
    salary: "₹36,000 - ₹63,840",
    salaryHindi: "₹36,000 - ₹63,840",
    website: "https://sbi.co.in",
    status: "Active",
    icon: "Landmark"
  },
  {
    id: "sbi-clerk-2025",
    title: "SBI Clerk Recruitment",
    titleHindi: "एसबीआई क्लर्क भर्ती",
    department: "State Bank of India",
    departmentHindi: "स्टेट बैंक ऑफ इंडिया",
    category: "Banking",
    vacancies: 6589,
    qualification: "Bachelor's Degree",
    qualificationHindi: "स्नातक डिग्री",
    ageLimit: "20-28 years",
    ageLimitHindi: "20-28 वर्ष",
    lastDate: "2025-08-26",
    salary: "₹19,900 - ₹47,920",
    salaryHindi: "₹19,900 - ₹47,920",
    website: "https://sbi.co.in",
    status: "Active",
    icon: "Landmark"
  },
  {
    id: "ibps-po-2025",
    title: "IBPS PO Recruitment",
    titleHindi: "आईबीपीएस पीओ भर्ती",
    department: "Institute of Banking Personnel",
    departmentHindi: "इंस्टीट्यूट ऑफ बैंकिंग पर्सनेल",
    category: "Banking",
    vacancies: 5208,
    qualification: "Bachelor's Degree",
    qualificationHindi: "स्नातक डिग्री",
    ageLimit: "20-30 years",
    ageLimitHindi: "20-30 वर्ष",
    lastDate: "2025-07-21",
    salary: "₹23,700 - ₹42,020",
    salaryHindi: "₹23,700 - ₹42,020",
    website: "https://ibps.in",
    status: "Active",
    icon: "Landmark"
  },
  {
    id: "ibps-clerk-2025",
    title: "IBPS Clerk Recruitment",
    titleHindi: "आईबीपीएस क्लर्क भर्ती",
    department: "Institute of Banking Personnel",
    departmentHindi: "इंस्टीट्यूट ऑफ बैंकिंग पर्सनेल",
    category: "Banking",
    vacancies: 10277,
    qualification: "Bachelor's Degree",
    qualificationHindi: "स्नातक डिग्री",
    ageLimit: "20-28 years",
    ageLimitHindi: "20-28 वर्ष",
    lastDate: "2025-08-21",
    salary: "₹19,900 - ₹47,920",
    salaryHindi: "₹19,900 - ₹47,920",
    website: "https://ibps.in",
    status: "Active",
    icon: "Landmark"
  },
  {
    id: "upsc-cse-2025",
    title: "UPSC Civil Services",
    titleHindi: "यूपीएससी सिविल सेवाएं",
    department: "Union Public Service Commission",
    departmentHindi: "संघ लोक सेवा आयोग",
    category: "Civil Services",
    vacancies: 1205,
    qualification: "Bachelor's Degree",
    qualificationHindi: "स्नातक डिग्री",
    ageLimit: "21-32 years",
    ageLimitHindi: "21-32 वर्ष",
    lastDate: "2025-02-21",
    salary: "₹56,100 - ₹2,50,000",
    salaryHindi: "₹56,100 - ₹2,50,000",
    website: "https://upsc.gov.in",
    status: "Upcoming",
    icon: "Scale"
  },
  {
    id: "bihar-police-2025",
    title: "Bihar Police Constable",
    titleHindi: "बिहार पुलिस कांस्टेबल",
    department: "Bihar Police",
    departmentHindi: "बिहार पुलिस",
    category: "State Govt",
    vacancies: 19828,
    qualification: "12th Pass",
    qualificationHindi: "12वीं पास",
    ageLimit: "18-25 years",
    ageLimitHindi: "18-25 वर्ष",
    lastDate: "2025-04-18",
    salary: "₹21,700 - ₹69,100",
    salaryHindi: "₹21,700 - ₹69,100",
    website: "https://csbc.bih.nic.in",
    status: "Active",
    icon: "Shield"
  },
  {
    id: "isro-scientist-2025",
    title: "ISRO Scientist/Engineer",
    titleHindi: "इसरो वैज्ञानिक/इंजीनियर",
    department: "Indian Space Research Organisation",
    departmentHindi: "भारतीय अंतरिक्ष अनुसंधान संगठन",
    category: "Technical",
    vacancies: 320,
    qualification: "B.Tech/B.E",
    qualificationHindi: "बी.टेक/बी.ई",
    ageLimit: "18-35 years",
    ageLimitHindi: "18-35 वर्ष",
    lastDate: "2025-06-16",
    salary: "₹56,100 - ₹1,77,500",
    salaryHindi: "₹56,100 - ₹1,77,500",
    website: "https://isro.gov.in",
    status: "Active",
    icon: "Rocket"
  },
  {
    id: "aiims-cra-2025",
    title: "AIIMS Common Recruitment",
    titleHindi: "एम्स कॉमन रिक्रूटमेंट",
    department: "All India Institute of Medical Sciences",
    departmentHindi: "अखिल भारतीय आयुर्विज्ञान संस्थान",
    category: "Medical",
    vacancies: 2300,
    qualification: "10th/12th/Graduation",
    qualificationHindi: "10वीं/12वीं/स्नातक",
    ageLimit: "18-35 years",
    ageLimitHindi: "18-35 वर्ष",
    lastDate: "2025-08-31",
    salary: "₹18,000 - ₹1,42,400",
    salaryHindi: "₹18,000 - ₹1,42,400",
    website: "https://aiimsexams.ac.in",
    status: "Active",
    icon: "Stethoscope"
  },
  {
    id: "india-post-gds-2025",
    title: "India Post GDS",
    titleHindi: "इंडिया पोस्ट जीडीएस",
    department: "Department of Posts",
    departmentHindi: "डाक विभाग",
    category: "Central Govt",
    vacancies: 21413,
    qualification: "10th Pass",
    qualificationHindi: "10वीं पास",
    ageLimit: "18-40 years",
    ageLimitHindi: "18-40 वर्ष",
    lastDate: "2025-03-03",
    salary: "₹12,000 - ₹29,380",
    salaryHindi: "₹12,000 - ₹29,380",
    website: "https://indiapost.gov.in",
    status: "Active",
    icon: "Mail"
  },
  {
    id: "coal-india-2025",
    title: "Coal India Management Trainee",
    titleHindi: "कोल इंडिया मैनेजमेंट ट्रेनी",
    department: "Coal India Limited",
    departmentHindi: "कोल इंडिया लिमिटेड",
    category: "PSU",
    vacancies: 434,
    qualification: "B.Tech/B.E",
    qualificationHindi: "बी.टेक/बी.ई",
    ageLimit: "18-30 years",
    ageLimitHindi: "18-30 वर्ष",
    lastDate: "2025-02-14",
    salary: "₹50,000 - ₹1,60,000",
    salaryHindi: "₹50,000 - ₹1,60,000",
    website: "https://coalindia.in",
    status: "Active",
    icon: "Factory"
  },
  {
    id: "bhel-2025",
    title: "BHEL Engineer Trainee",
    titleHindi: "भेल इंजीनियर ट्रेनी",
    department: "Bharat Heavy Electricals Limited",
    departmentHindi: "भारत हैवी इलेक्ट्रिकल्स लिमिटेड",
    category: "PSU",
    vacancies: 400,
    qualification: "B.Tech/B.E",
    qualificationHindi: "बी.टेक/बी.ई",
    ageLimit: "18-27 years",
    ageLimitHindi: "18-27 वर्ष",
    lastDate: "2025-02-28",
    salary: "₹40,000 - ₹1,40,000",
    salaryHindi: "₹40,000 - ₹1,40,000",
    website: "https://bhel.com",
    status: "Active",
    icon: "Factory"
  },
  {
    id: "mp-tet-2025",
    title: "MP TET Varg 2",
    titleHindi: "एमपी टीईटी वर्ग 2",
    department: "Madhya Pradesh Professional Examination Board",
    departmentHindi: "मध्य प्रदेश व्यावसायिक परीक्षा मंडल",
    category: "Teaching",
    vacancies: 18650,
    qualification: "B.Ed/D.Ed",
    qualificationHindi: "बी.एड/डी.एड",
    ageLimit: "21-40 years",
    ageLimitHindi: "21-40 वर्ष",
    lastDate: "2025-08-31",
    salary: "₹32,800 - ₹1,03,600",
    salaryHindi: "₹32,800 - ₹1,03,600",
    website: "https://peb.mp.gov.in",
    status: "Active",
    icon: "GraduationCap"
  },
  {
    id: "reet-mains-2025",
    title: "REET Mains Teacher",
    titleHindi: "रीट मेन्स शिक्षक",
    department: "Rajasthan Education Department",
    departmentHindi: "राजस्थान शिक्षा विभाग",
    category: "Teaching",
    vacancies: 7759,
    qualification: "B.Ed/D.Ed",
    qualificationHindi: "बी.एड/डी.एड",
    ageLimit: "18-40 years",
    ageLimitHindi: "18-40 वर्ष",
    lastDate: "2025-04-15",
    salary: "₹23,700 - ₹1,12,400",
    salaryHindi: "₹23,700 - ₹1,12,400",
    website: "https://rajeduboard.rajasthan.gov.in",
    status: "Upcoming",
    icon: "GraduationCap"
  },
  {
    id: "ib-acio-2025",
    title: "IB ACIO Recruitment",
    titleHindi: "आईबी एसीआईओ भर्ती",
    department: "Intelligence Bureau",
    departmentHindi: "इंटेलिजेंस ब्यूरो",
    category: "Defense",
    vacancies: 3717,
    qualification: "Bachelor's Degree",
    qualificationHindi: "स्नातक डिग्री",
    ageLimit: "18-27 years",
    ageLimitHindi: "18-27 वर्ष",
    lastDate: "2025-08-10",
    salary: "₹44,900 - ₹1,42,400",
    salaryHindi: "₹44,900 - ₹1,42,400",
    website: "https://mha.gov.in",
    status: "Active",
    icon: "Shield"
  },
  {
    id: "aai-atc-2025",
    title: "AAI Junior Executive ATC",
    titleHindi: "एएआई जूनियर एग्जीक्यूटिव एटीसी",
    department: "Airports Authority of India",
    departmentHindi: "एयरपोर्ट्स अथॉरिटी ऑफ इंडिया",
    category: "Aviation",
    vacancies: 309,
    qualification: "B.Tech/B.Sc",
    qualificationHindi: "बी.टेक/बी.एससी",
    ageLimit: "18-27 years",
    ageLimitHindi: "18-27 वर्ष",
    lastDate: "2025-05-24",
    salary: "₹40,000 - ₹1,40,000",
    salaryHindi: "₹40,000 - ₹1,40,000",
    website: "https://aai.aero",
    status: "Active",
    icon: "Plane"
  }
];

export const jobCategories = [
  "All",
  "Central Govt",
  "State Govt",
  "Banking",
  "Railway",
  "Defense",
  "Teaching",
  "Medical",
  "Technical",
  "PSU",
  "Civil Services",
  "Aviation"
];
